"""Add email_sent_status to Order model

Revision ID: 114481d732b8
Revises: 5f087b86e6a9
Create Date: 2025-07-23 10:05:22.667388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114481d732b8'
down_revision = '5f087b86e6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_status', sa.Boolean(), nullable=False, server_default=sa.text("false")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('email_sent_status')

    # ### end Alembic commands ###
