"""Add display_order column to artwork table

Revision ID: 1e55ad0b3762
Revises: 
Create Date: 2025-09-18 20:28:00.297876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e55ad0b3762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hsn_code')
    op.drop_table('cart_item')
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.drop_column('hsn_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('display_order')

    op.create_table('cart_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('artwork_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price_before_gst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cgst_percentage_applied', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('sgst_percentage_applied', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('igst_percentage_applied', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('ugst_percentage_applied', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('cess_percentage_applied', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('gst_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cess_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.id'], name=op.f('cart_item_artwork_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('cart_item_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_item_pkey'))
    )
    op.create_table('hsn_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cgst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sgst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('igst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hsn_code_pkey')),
    sa.UniqueConstraint('code', name=op.f('hsn_code_code_key'))
    )
    # ### end Alembic commands ###
