"""Add email_sent_status to Order model

Revision ID: 5f087b86e6a9
Revises: 25fead9207a9
Create Date: 2025-07-23 10:02:36.928242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f087b86e6a9'
down_revision = '25fead9207a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('email_sent_status')

    # ### end Alembic commands ###
