"""Add hsn_code to Artwork model

Revision ID: 79d6b1ba85bd
Revises: 1e55ad0b3762
Create Date: 2025-09-26 00:17:41.863695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d6b1ba85bd'
down_revision = '1e55ad0b3762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('hsn_code')

    # ### end Alembic commands ###
