"""Add invoice_file_url to Order model

Revision ID: 903609f7316c
Revises: a2851029aae7
Create Date: 2025-09-29 19:32:44.631969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903609f7316c'
down_revision = 'a2851029aae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_file_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('invoice_file_url')

    # ### end Alembic commands ###
