"""Add gst_number column to Order table

Revision ID: a2851029aae7
Revises: a50e76b8d212
Create Date: 2025-09-26 22:55:11.991430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2851029aae7'
down_revision = 'a50e76b8d212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('gst_number')

    # ### end Alembic commands ###
