"""Add hsn_description to Artwork model

Revision ID: a50e76b8d212
Revises: 79d6b1ba85bd
Create Date: 2025-09-26 00:47:48.012657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50e76b8d212'
down_revision = '79d6b1ba85bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('hsn_description')

    # ### end Alembic commands ###
