"""Add discount_price to Artwork

Revision ID: a7bc208679d4
Revises: f0e1e682a234
Create Date: 2025-10-11 20:53:28.963497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bc208679d4'
down_revision = 'f0e1e682a234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###
